title: ---
description: ---

markdown: kramdown
plugins:
  - jekyll-remote-theme

remote_theme: abhinavs/moonwalk@master

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["lsquo", "rsquo", "ldquo", "rdquo"]
  toc_levels: 1..3
